name: Refresh data
on:
  schedule:
    - cron: "17 7 * * *"   # daily 7:17 UTC
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: node scripts/fetch-cfbd-static.js
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
      - run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          git commit -m "chore(data): refresh" || echo "no changes"
          git push
